eventpoll.h: add missing epoll event masks
[resend due to me forgetting to cc: linux-api the first time around I
posted these back on Feb 23]

From: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

For some reason these values are not in the uapi header file, so any
libc has to define it themselves.  To prevent them from needing to do
this, just have the kernel provide the correct values.

Reported-by: Elliott Hughes <enh@google.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

[ Upstream commit 7e040726850a106587485c21bdacc0bfc8a0cbed ]

Backported-by: Vladimir Oltean <olteanv@gmail.com>

Reason:

bootable/recovery/minui/events.cpp:105:19: error: use of undeclared identifier 'EPOLLIN'
      ev.events = EPOLLIN | EPOLLWAKEUP;
                  ^
bootable/recovery/minui/events.cpp:149:15: error: use of undeclared identifier 'EPOLLIN'
  ev.events = EPOLLIN | EPOLLWAKEUP;
              ^
bootable/recovery/minui/events.cpp:197:20: error: use of undeclared identifier 'EPOLLIN'
    if (epevents & EPOLLIN) {

Change-Id: If0ed0e6af33c7b56c55072f4c58e6c926e61bcd6